travis:
  secure:
    BINSTAR_TOKEN: YS57/jxkhpe65XiMZmHMp8UH0LtdsRhgo3Yq9STUacsmyQkJr0rxE4OBqQNetsnCOLrDl1CLO13ZKSuF7Chy287CiZZKT/eqoBA4z6LjUhE3ReAcDQp8uEbqaltP9uVsyu2hhZtcW17rPhqq+uJfm5aXZtVRHqEQLHA5dFfYOKDMJbs48DpnihCn/oX/ACUhEazPmSIJiiLRWmcAen0BSxAvjdQrnfjcRXNPtT8Q1RPHLhButLs2c62OfrPB+s9WuEwShXA99gn3I42BL5PW2YDiQOAE5/4fc8hFy9CxQAPDjVF5gjTsmm69bQXgRVvnjSyjpjDPlBSxOlLGWc9knPVjCyunRuBeJmVlTvDThXtvdcTFpsRL/VoP7XuOq0D6529HeAOEKxDIfvy/Ce4x1sc3PpxI4eTb7dGAi0Vs8rAXNssiTpv14Z+0aCwAjk65eXLRiRnBiSKV4AopDNWx18Unz5n5NjBevUDKISs4ELFujOeKRWdLsFXm4miUsB3/2nY00iBY0Te/XNDaLI4TdSPmxFPRiHHU9H+s/ALvBANKjRYN0YTWRHcToIMaKmGzIgvf40/jbAd3aZXsvOMDYZbZyfJ9uXfBqsRU67V4W7qUbbm7pPcBn3jHkvnbSMYZyF9i6EB4rhzavcydIbwISukHqN1nXLpWIk14AAkzB1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
