travis:
  secure:
    BINSTAR_TOKEN: lJ00idVAcmgXEXqkffb2sKBqpufh3U4JvquYyNfA/KsJOYWhhyaJXNVYXt4t/3RDQNOwb4oaQQsjhJXVINR/rLFt7Pny64UkQebKMyJbYOs2TL+7NxM8StzJFM0s4ky1kKWbla+z5MSBrQWEL4dS4Lfeg2qFn9D46mbs99kwcVl9s+Dm3mW65KmVi6KY54tlg+yrT3bMabk515iRf/UTEpVuOi+Fe3K2UO1rqCUql/a0sId3Ve+vAKjlnz4Mq9YFmesAStqUJQqsSZZIiv8WI9zeJCM6nKvJQq8mHoVNpqtKARkvBC4ekyeJDFe8GkvXakfIUHwEJdNWBncdeoWP36c6C8cjyU/ekyXikVafBdH4lVWy/fgvvIicNxOeIVzFxz3mEAMQel+2z3ZHK1k271sChwmtLXIZnLAy2bXz+JDcftMvPokEyHkWMFVuxYXu7NKEbWM5KGV2/iAFcik+Ba1ibx/6oG4ufcHoot+2/xfLdQSuiRdMV9W8ZLUr9BpSXcNzXU+aZPQ6mkm19XmzLYMHvnZx49xMSdgIuGkcxTa/WOkWcXelJb8rZs7SHm6g95TErw79uhR5SgtwtUtZ6nb0VXAy+l7B11iSx71ovIyoZnpS/lq5JpfbX+U2kKB+nPCZULmM/9/2ljSi1aQqs6Y9Q4zorm5+8P6I/Adlg7k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
