travis:
  secure:
    BINSTAR_TOKEN: f0wliQLX93PpPDkwRP56lP5yxWu6g81gsNFc93WFQMq9X+IiuxKJG2F5Mneupn81cA6I8DeUNL/p3IfjOqg18EeUgldgupID9AuCW0qddEAyeii90d5hNyVJQj3IwDZcaKGoRp7xspljJHFytDEf+eGJ+yIsyHKMZ46Lm5IejkbXBwG46wyOzxpMPWPS1DRVRaHxil7TZQyCPzgW+Zf7KRbQEo+E3cTsPaamaRH+oorKaSocj7FSMmX4cPOpsINl2ApkPG1nX46j4Iilkf9CZWhgvqs7Y59AJLRC2v/3EaVno+bLeCXVsgr7pzRdQN59W8rQuLPntrEHRDU8s4/B7EEGTw5WPqG3lsvxGMDpvIEPmOSr/6yZduuCXg1hv/nxJemvr3ck/lmjYlbBk5p/oIQ9c2fvjgM1vF/DuUxlStH7MnOLv+ahTGhfRksydJfdFnrJaWjvk0ni67FYvCw90YvNzz1MzZgJGya1/4a0aqohlYrMfydCXmm38qbG6sHnFuUfKDp20ECfJLE+rp84dnFqRWz2InHYFhZ/C3EfU3wGgzkPHah1JoFT11BV5OeNMzipkD3LCtgRwToyWWQ/PpLrHQj5Q50i0cwqzxy30nilaHmDcjQ3CB0h5kjNJsOx60yU3mT0E9A6D2sibkSF35wPM3yviXc/gytQBPu7Zk8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
